### PR TITLE
UI Fixes and Tweaks from user testing

### LINKED ISSUE #116: ExpandedViewMode goal title edit has bug where content gets overridden
This occurs intermittently, and seems to be a byproduct of a refetching of existing Goals... thus leading to it reseting the goal to its original pre-edit title, and wiping out your edits.

VERY ANNOYING. Fix asap

Also occurs while editing the 'description' field

### PR DESCRIPTION
**Pull request by Connoropolous**
closes #116

### CODE REVIEW

File: src/components/PriorityPicker/PriorityPicker.js [hunk 1]
```diff
@@ -261,10 +261,10 @@ function Priority({
       return value.agent_address === whoami.entry.address
     })
     if (!vote) return
-    archiveVoteOfGoal(vote.address).then(() => {
```
Comment (Connoropolous) [inline src/components/PriorityPicker/PriorityPicker.js]: This was the source of the "myVote is undefined" bug that would crash the screen, when you archived a goal vote
